apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  labels:
    app: notes-app
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: aniket036/django-n-app:latest
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: DB_NAME
          value: "notesdb"
        - name: DB_USER
          value: "notesuser"
        - name: DB_PASSWORD
          value: "notessecret"
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 20
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 5

